columns:
  datetime:
    - decision_date
    - case_received_date
  numerical:
  drop:
   - case_no
   - case_number
  categorical:
    - case_status
    - class_of_admission
    
cleaning_rules:
  string_columns:
    strip_whitespace: true
    to_lowercase: true
  
  datetime_format: '%Y-%m-%d %H:%M:%S'
  
  missing_values:
    numerical:
      method: mean
    categorical:
      method: mode
      
validation_rules:
  age:
    min: 0
    max: 120
  salary:
    min: 0